version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: ~/w
    steps:
      - checkout
      - run: |
          node -v
          npm -v
          google-chrome --version
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run codecov
